#ifndef _SVCCONVERTER_SRC_LABEL_STRING_H_
#define _SVCCONVERTER_SRC_LABEL_STRING_H_

#ifndef NOMINMAX
#define NOMINMAX 1
#endif

#include <string>
#include <unordered_map>
#include <wx/wxprec.h>
#ifndef WX_PRECOMP
#include <wx/wx.h>
#endif // WX_PRECOMP
#include <windows.h>

std::unordered_map<unsigned char, wxString> key_str = {
{VK_LBUTTON, "Mouse Left"},
{VK_RBUTTON, "Mouse Right"},
{VK_CANCEL, "Ctrl Break"},
{VK_MBUTTON, "Mouse Middle"},
{VK_XBUTTON1, "Mouse extend 1"},
{VK_XBUTTON2, "Mouse extend 2"},
{VK_BACK, "Backspace"},
{VK_TAB, "Tab"},
{VK_CLEAR, "Clear"},
{VK_RETURN, "Enter"},
{VK_SHIFT, "Shift"},
{VK_CONTROL, "Ctrl"},
{VK_MENU, "Alt"},
{VK_PAUSE, "Pause"},
{VK_CAPITAL, "Caps Lock"},
{VK_KANA, "Kana"},
{VK_HANGEUL, "Hangeul"},
{VK_JUNJA, "Junja"},
{VK_FINAL, "Final"},
{VK_KANJI, L"漢字"},
{VK_ESCAPE, "Esc"},
{VK_CONVERT, L"変換"},
{VK_NONCONVERT, L"無変換"},
{VK_ACCEPT, "Accept"},
{VK_MODECHANGE, "Mode change"},
{VK_SPACE, "Space"},
{VK_PRIOR, "Page Up"},
{VK_NEXT, "Page Down"},
{VK_END, "End"},
{VK_HOME, "Home"},
{VK_LEFT, "Left"},
{VK_UP, "Up"},
{VK_RIGHT, "Right"},
{VK_DOWN, "Down"},
{VK_SELECT, "Select"},
{VK_PRINT, "Print"},
{VK_EXECUTE, "Execute"},
{VK_SNAPSHOT, "PrintScreen"},
{VK_INSERT, "Insert"},
{VK_DELETE, "Delete"},
{VK_HELP, "Help"},
{VK_LWIN, "Left Windows"},
{VK_RWIN, "Right Windows"},
{VK_APPS, "Application"},
{VK_SLEEP, "Sleep"},
{VK_NUMPAD0, "Numpad 0"},
{VK_NUMPAD1, "Numpad 1"},
{VK_NUMPAD2, "Numpad 2"},
{VK_NUMPAD3, "Numpad 3"},
{VK_NUMPAD4, "Numpad 4"},
{VK_NUMPAD5, "Numpad 5"},
{VK_NUMPAD6, "Numpad 6"},
{VK_NUMPAD7, "Numpad 7"},
{VK_NUMPAD8, "Numpad 8"},
{VK_NUMPAD9, "Numpad 9"},
{VK_MULTIPLY, "Numpad *"},
{VK_ADD, "Numpad +"},
{VK_SEPARATOR, "Separator"},
{VK_SUBTRACT, "-"},
{VK_DECIMAL, "."},
{VK_DIVIDE, "/"},
{VK_F1, "F1"},
{VK_F2, "F2"},
{VK_F3, "F3"},
{VK_F4, "F4"},
{VK_F5, "F5"},
{VK_F6, "F6"},
{VK_F7, "F7"},
{VK_F8, "F8"},
{VK_F9, "F9"},
{VK_F10, "F10"},
{VK_F11, "F11"},
{VK_F12, "F12"},
{VK_F13, "F13"},
{VK_F14, "F14"},
{VK_F15, "F15"},
{VK_F16, "F16"},
{VK_F17, "F17"},
{VK_F18, "F18"},
{VK_F19, "F19"},
{VK_F20, "F10"},
{VK_F21, "F21"},
{VK_F22, "F22"},
{VK_F23, "F23"},
{VK_F24, "F24"},
{VK_NUMLOCK, "NumLock"},
{VK_SCROLL, "ScrollLock"},
{VK_LSHIFT, "Left Shift"},
{VK_RSHIFT, "Right Shift"},
{VK_LCONTROL, "Left Ctrl"},
{VK_RCONTROL, "Right Ctrl"},
{VK_LMENU, "Left Alt"},
{VK_RMENU, "Right Alt"},
{VK_BROWSER_BACK, "Browser Back"},
{VK_BROWSER_FORWARD, "Browser Forward"},
{VK_BROWSER_REFRESH, "Browser Refresh"},
{VK_BROWSER_STOP, "Browser Stop"},
{VK_BROWSER_SEARCH, "Browser Search"},
{VK_BROWSER_FAVORITES, "Browser Favorites"},
{VK_BROWSER_HOME, "Browser Home"},
{VK_VOLUME_MUTE, "Volume Mute"},
{VK_VOLUME_DOWN, "Volume Down"},
{VK_VOLUME_UP, "Volume Up"},
{VK_MEDIA_NEXT_TRACK, "Next Track"},
{VK_MEDIA_PREV_TRACK, "Previous Track"},
{VK_MEDIA_STOP, "Media Stop"},
{VK_MEDIA_PLAY_PAUSE, "Media Pause"},
{VK_LAUNCH_MAIL, "Launch Mail"},
{VK_LAUNCH_MEDIA_SELECT, "Media Select"},
{VK_LAUNCH_APP1, "Launch App 1"},
{VK_LAUNCH_APP2, "Launch App 2"},
{VK_OEM_1, "OEM :"},
{VK_OEM_PLUS, "OEM ;"},
{VK_OEM_COMMA, "OEM ,"},
{VK_OEM_MINUS, "OEM -"},
{VK_OEM_PERIOD, "OEM ."},
{VK_OEM_2, "OEM /"},
{VK_OEM_3, "OEM @"},
{VK_OEM_4, "OEM ["},
{VK_OEM_5, "OEM \\ |"},
{VK_OEM_6, "OEM ]"},
{VK_OEM_7, "OEM ^"},
{VK_OEM_8, "OEM 8"},
{VK_OEM_AX, "OEM AX"},
{VK_OEM_102, "OEM \\ _"},
{VK_ICO_HELP, "OEM ICO Help"},
{VK_ICO_00, "OEM ICO 00"},
{VK_PROCESSKEY, "Process"},
{VK_ICO_CLEAR, "OEM ICO Clear"},
{VK_PACKET, "Packet"},
{VK_OEM_RESET, "OEM Reset"},
{VK_OEM_JUMP, "OEM Jump"},
{VK_OEM_PA1, "OEM PA1"},
{VK_OEM_PA2, "OEM PA2"},
{VK_OEM_PA3, "OEM PA3"},
{VK_OEM_WSCTRL, "OEM WSCtrl"},
{VK_OEM_CUSEL, "OEM CUSEL"},
{VK_OEM_ATTN, "OEM CapsLock"},
{VK_OEM_FINISH, "OEM Finish"},
{VK_OEM_COPY, L"カタカナ ひらがな"},
{VK_OEM_AUTO, L"全角/半角"},
{VK_OEM_ENLW, "OEM ENLW"},
{VK_OEM_BACKTAB, L"Alt + カタカナ ひらがな"},
{VK_ATTN, "Attn"},
{VK_CRSEL, "CrSel"},
{VK_EXSEL, "ExSel"},
{VK_EREOF, "Erase EOF"},
{VK_PLAY, "Play"},
{VK_ZOOM, "Zoom"},
{VK_NONAME, "No Name"},
{VK_PA1, "PA1"},
{VK_OEM_CLEAR, "Clear"},
{0x30, "0"},
{0x31, "1"},
{0x32, "2"},
{0x33, "3"},
{0x34, "4"},
{0x35, "5"},
{0x36, "6"},
{0x37, "7"},
{0x38, "8"},
{0x39, "9"},
{0x41, "A"},
{0x42, "B"},
{0x43, "C"},
{0x44, "D"},
{0x45, "E"},
{0x46, "F"},
{0x47, "G"},
{0x48, "H"},
{0x49, "I"},
{0x4a, "J"},
{0x4b, "K"},
{0x4c, "L"},
{0x4d, "M"},
{0x4e, "N"},
{0x4f, "O"},
{0x50, "P"},
{0x51, "Q"},
{0x52, "R"},
{0x53, "S"},
{0x54, "T"},
{0x55, "U"},
{0x56, "V"},
{0x57, "W"},
{0x58, "X"},
{0x59, "Y"},
{0x5a, "Z"}
};

#endif // _SVCCONVERTER_SRC_LABEL_STRING_H_